map_update_interval: 0.5
minimumScore: 5
linearUpdate: 0.1
angularUpdate: 0.01
maxRange: 110.0
maxUrange: 100.0
sigma: 0.05
kernelSize: 1
lstep: 0.05
astep: 0.05
iterations: 5
lsigma: 0.075
ogain: 3.0
lskip: 0
srr: 0.1
srt: 0.2
str: 0.1
stt: 0.2
temporalUpdate: 0.5
resampleThreshold: 0.5
particles: 30
xmin: -100.0
ymin: -100.0
xmax: 100.0
ymax: 100.0
delta: 0.05
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005
