agvs:
# Velocity controllers
  front_right_wheel_joint_controller:
    type: velocity_controllers/JointVelocityController
    joint: front_right_wheel_joint
    pid: {p: 1000.0, i: 0.01, d: 100.0}

  front_left_wheel_joint_controller:
    type: velocity_controllers/JointVelocityController
    joint: front_left_wheel_joint
    pid: {p: 1000.0, i: 0.01, d: 100.0}

  back_right_wheel_joint_controller:
    type: velocity_controllers/JointVelocityController
    joint: back_right_wheel_joint
    pid: {p: 1000.0, i: 0.01, d: 100.0}

  back_left_wheel_joint_controller:
    type: velocity_controllers/JointVelocityController
    joint: back_left_wheel_joint
    pid: {p: 1000.0, i: 0.01, d: 100.0}

# Position controllers
# Be careful with the selection of the pid values, e.g. d: 50.0 produces a nan in the velocity ???
  front_right_motor_wheel_joint_controller:
    type: effort_controllers/JointPositionController
    joint: front_right_motor_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  front_left_motor_wheel_joint_controller:
    type: effort_controllers/JointPositionController
    joint: front_left_motor_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  back_right_motor_wheel_joint_controller:
    type: effort_controllers/JointPositionController
    joint: back_right_motor_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
   
  back_left_motor_wheel_joint_controller:
    type: effort_controllers/JointPositionController
    joint: back_left_motor_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint_read_state_controller:
    type: joint_state_controller/JointStateController 
    publish_rate: 100.0
